### ISSUE TITLE
pls fix comit

### ISSUE THREAD

**Issue by alexanderberry** [TheCompSciNoob/Synthesizer#1]
је врло лоша порука са поруком молим вас да то поправите
is of very bad commit message pls do the fixing

**Comment by alexanderberry** [comment]
@TheCompSciNoob @TheCompSciNoob @TheCompSciNoob @TheCompSciNoob @TheCompSciNoob @TheCompSciNoob @TheCompSciNoob @TheCompSciNoob @TheCompSciNoob @TheCompSciNoob 
@TheCompSciNoob @TheCompSciNoob @TheCompSciNoob 
mincraf

**Comment by kyroschow** [comment]
fake news
